def test_should_fail_if_patient_already_exist():
    ...

def test_should_fail_if_missing_data():
    ...

def test_should_fail_if_no_patient_consent():
    ...

def test_should_fail_if_no_guardian_consent_for_minor():
    ...

def test_should_return_id():
    ...